import "~/styles/globals.css";

import { Inter, Noto_Music } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const noto = Noto_Music({
  weight: "400",
  subsets: ["music"],
  variable: "--font-music",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} ${noto.variable}`}>
        {children}
      </body>
    </html>
  );
}
